import type { PortfolioItem } from '@/types';

export const PORTFOLIO_DATA: PortfolioItem[] = [
  {
    id: 'e1',
    title: '2023 강한소상공인 성장지원사업 글로벌유형 1차 오디션',
    titleEn: '2023 Strong Small Business Growth Support Global Audition',
    description: '100명의 소상공인이 참여한 오디션 쇼 형태의 글로벌 진출 지원 행사',
    descriptionEn: 'Global expansion audition show with 100 small business owners',
    images: [],
    year: 2023,
    order: 1,
    featured: true,
    date: '2023. 6. 27. - 6. 29.',
    venue: '롯데월드타워 123라운지',
    venueEn: 'Lotte World Tower 123 Lounge',
    organizer: '중소벤처기업부 / 소상공인시장진흥공단',
    organizerEn: 'Ministry of SMEs and Startups / Small Enterprise and Market Service',
    concept: '창의적 아이디어를 가진 소상공인과 혁신 역량을 갖춘 파트너와의 협력 및 사업화를 지원하여 경쟁력있는 소상공인을 발굴하고 육성하는 사업으로 100명의 소상공인들이 참여해 5분 발표, 5분 질의응답을 하는 오디션 쇼 형태로 진행되었습니다.',
    planningPoint: '대한민국에서 가장 높은 곳, 123층의 전경이 보이는 공간의 특징을 살려 행사장을 디자인하였으며 글로벌 진출을 희망하는 소상공인들의 니즈를 담은 참여 이벤트로, 세계지도 이벤트월을 설치하여 참여 요소를 더했습니다.',
  },
  {
    id: 'e2',
    title: '경남형 스타트업&대학특화 청년창업가 액셀러레이팅 합동 성과공유회',
    titleEn: 'Gyeongnam Startup & University Youth Entrepreneur Accelerating Joint Showcase',
    description: '경남 지역 스타트업 발굴과 투자유치를 위한 데모데이 및 시상식',
    descriptionEn: 'Demo day and awards for Gyeongnam regional startup discovery and investment',
    images: [],
    year: 2023,
    order: 2,
    date: '2023. 12. 1.',
    venue: '경남창조경제혁신센터 611호',
    venueEn: 'Gyeongnam Center for Creative Economy & Innovation',
    organizer: '경상남도 / 경남창조경제혁신센터',
    organizerEn: 'Gyeongsangnam-do / Gyeongnam CCEI',
    concept: '경남 지역의 10년 미만 특화 분야 스타트업 발굴과 관계자 네트워킹을 통한 투자유치 및 글로벌 진출을 모색하고자 일년간 진행된 액셀러레이팅 참여 우수기업의 데모데이, 시상식을 통해 성취도 향상을 목표로 하는 경남지역 액셀러레이팅 통합 성과 공유회입니다.',
    planningPoint: '행사의 부제 \'WAKE YOU 업(業)!\'을 제안하여 키비주얼에 반영하였으며 빠른 순서로 진행되는 데모데이를 플래닝펍만의 노하우로 원활히 운영하였습니다.',
  },
  {
    id: 'e3',
    title: '2025년 소상공인 협업활성화 공동사업(산업형) 및 LIPS 성과공유회',
    titleEn: '2025 Small Business Collaboration & LIPS Performance Showcase',
    description: '협업체 성과 발표와 전시, 멘토링으로 구성된 성과공유회',
    descriptionEn: 'Performance showcase with presentations, exhibitions, and mentoring',
    images: [],
    year: 2025,
    order: 3,
    featured: true,
    date: '2025. 12. 4.',
    venue: '위플레이스 강남 2호점',
    venueEn: 'WePlace Gangnam Branch 2',
    organizer: '중소벤처기업부, 소상공인시장진흥공단, 엔피프틴파트너스',
    organizerEn: 'Ministry of SMEs and Startups, SEMAS, N15 Partners',
    concept: '2025년 소상공인 협업활성화 공동사업(산업형)의 성과를 공유·확산하기 위해 기획된 행사로, 한 해 동안 협업체가 창출한 비즈니스 성과와 성장 가능성을 업계 관계자에게 직접 소개하는 데 목적을 두었습니다.',
    planningPoint: '협업체 성과를 효과적으로 전달하기 위해 발표·전시·멘토링으로 이어지는 단계형 프로그램으로 설계했습니다. 협업체의 소개 영상과 실물 전시를 결합해 몰입도를 높였으며, 관계자 간 심층 대화를 유도하는 라운드 테이블 멘토링을 운영해 후속 협력 가능성을 강화했습니다.',
  },
  {
    id: 'e4',
    title: '제3회 오산시 진로진학박람회',
    titleEn: '3rd Osan City Career & College Fair',
    description: '온라인 개최된 오산시 최초의 교육 박람회',
    descriptionEn: 'Osan City\'s first online education fair',
    images: [],
    year: 2021,
    order: 4,
    date: '2021. 7. 5. - 16.',
    venue: '오산 소리울 도서관',
    venueEn: 'Osan Soriul Library',
    organizer: '오산시 / 오산교육재단',
    organizerEn: 'Osan City / Osan Education Foundation',
    concept: '온라인으로 개최된 오산시의 첫 교육 박람회로 온라인 박람회를 위한 홈페이지를 신규 개설하여 진로·메이커 교육 온라인 체험을 제공하고 청소년 진로 도움을 위해 오산시 내 고등학교 홍보영상을 별도 제작하는 등 다양한 진로 진학 콘텐츠를 제작하였습니다.',
    planningPoint: '기존의 정형화된 홍보영상 형식에서 벗어나 방송 예능의 인터뷰 & 퀴즈쇼 형식을 차용하여 시나리오를 작성, 촬영 및 편집하여 8개 고교 홍보영상을 제작하였습니다.',
  },
  {
    id: 'e5',
    title: '2025 오늘전통 창업 통합 데모데이',
    titleEn: '2025 Today Tradition Startup Demo Day',
    description: '부산불꽃축제와 함께 진행된 전통문화 기반 청년 창업 데모데이',
    descriptionEn: 'Traditional culture youth startup demo day held with Busan Fireworks Festival',
    images: [],
    year: 2025,
    order: 5,
    date: '2025. 11. 15.',
    venue: '광안리 수영구 민락로',
    venueEn: 'Gwangalli, Suyeong-gu, Busan',
    organizer: '문화체육관광부, 한국공예·디자인문화진흥원, 엔피프틴파트너스, 씨엔티테크, 뉴키즈인베스트먼트',
    organizerEn: 'Ministry of Culture, KCDF, N15 Partners, CNT Tech, New Kids Investment',
    concept: '오늘전통 창업 통합 데모데이는 전통문화 기반의 청년 창업 아이템을 소개하는 행사로, 부산불꽃축제와 함께 진행되어 큰 관심을 모았습니다.',
    planningPoint: '행사는 발표, 전시, 멘토링으로 구성되어 창업가들의 아이템을 IR 피칭과 실물 전시를 통해 소개했습니다. 라운드 테이블 멘토링을 통해 심층적인 대화와 후속 협력 가능성을 논의할 수 있었습니다.',
  },
  {
    id: 'e6',
    title: '2024 전통 기록문화 창작 콘퍼런스&공모전 홈커밍',
    titleEn: '2024 Traditional Record Culture Creative Conference & Homecoming',
    description: 'K-콘텐츠의 동력이 되는 전통 기록문화 콘퍼런스 및 공모전 네트워킹',
    descriptionEn: 'Conference on traditional record culture as K-content driving force',
    images: [],
    year: 2024,
    order: 6,
    date: '2024. 8. 10.',
    venue: '메리츠화재연수원 대강의장',
    venueEn: 'Meritz Fire Training Center Grand Hall',
    organizer: '문화체육관광부 / 한국국학진흥원',
    organizerEn: 'Ministry of Culture / Korean Studies Advancement Center',
    concept: '"K-콘텐츠의 동력 : 전통 기록문화의 미래를 이끄는 공모전들"이라는 주제로 전통 기록자료 대중화를 위한 콘퍼런스를 운영하였습니다. 10년의 역사를 가진 공모전의 홈커밍을 운영하여 참가자간 네트워킹을 진행하였습니다.',
  },
  {
    id: 'e7',
    title: '2025년 요양보호가족휴식제도 성과공유회',
    titleEn: '2025 Caregiver Family Rest Program Performance Showcase',
    description: '봉사활동 성과 공유 및 우수 봉사자 표창 행사',
    descriptionEn: 'Volunteer achievement sharing and outstanding volunteer awards ceremony',
    images: [],
    year: 2025,
    order: 7,
    date: '2025. 11. 25.',
    venue: '영등포아트홀',
    venueEn: 'Yeongdeungpo Art Hall',
    organizer: '영등포구청',
    organizerEn: 'Yeongdeungpo District Office',
    concept: '지역사회 봉사활동의 성과를 공유하고, 봉사자들의 헌신과 공로를 공식적으로 인정하기 위해 마련된 행사입니다.',
    planningPoint: '봉사 활동 사례 공유와 표창 수여 중심의 프로그램 구성으로, 참가자들이 봉사의 가치를 직접 체감할 수 있도록 설계했습니다. 봉사자 연령대를 고려한 레크레이션 활동으로 네트워크 형성과 소속감 강화를 도모했습니다.',
  },
  {
    id: 'e8',
    title: '2025 K-인문 페스티벌',
    titleEn: '2025 K-Humanities Festival',
    description: '인문의 가치를 재조명하는 축제형 학술 프로그램',
    descriptionEn: 'Festival-style academic program highlighting humanities values',
    images: [],
    year: 2025,
    order: 8,
    date: '2025. 11. 4. - 11. 8.',
    venue: '안동국제컨벤션센터',
    venueEn: 'Andong International Convention Center',
    organizer: '국립경국대학교 글로컬대학추진단',
    organizerEn: 'Gyeongbuk National University Glocal University Division',
    concept: '인문의 가치를 재조명하고 미래 인문 생태계를 연결하는 축제형 학술 프로그램으로, 세대·지역·기관 간 교류의 장을 마련했습니다.',
    planningPoint: '대학 및 지역 기관과의 연계 기반을 구축해 유기적인 프로그램 동선을 설계했으며, 강연·체험·전시가 자연스럽게 연결되는 공간 연출을 통해 관람 경험의 몰입도를 높였습니다.',
  },
  {
    id: 'e9',
    title: '2023 신사업창업사관학교 네트워킹데이',
    titleEn: '2023 New Business Startup Academy Networking Day',
    description: '졸업기업 간 협업 및 총동문회 네트워킹 행사',
    descriptionEn: 'Alumni networking event for startup academy graduates',
    images: [],
    year: 2023,
    order: 9,
    date: '2023. 7. 13. - 14.',
    venue: '전주 라한호텔',
    venueEn: 'Jeonju Lahan Hotel',
    organizer: '소상공인시장진흥공단',
    organizerEn: 'Small Enterprise and Market Service',
    concept: '신사업창업사관학교 졸업기업 간 보유 자원의 연결 및 협업으로 새로운 비즈니스를 발굴하고 총동문회 창단에 따라 안정적인 정착을 위한 네트워킹 자리로 마련되었습니다.',
    planningPoint: '참가자들의 네트워킹을 위한 레크리에이션 프로그램과 지역(전주) 진행 행사를 고려한 수송 지원 등 운영계획을 수립하여 참가자 편의를 높였습니다.',
  },
  {
    id: 'e10',
    title: '2022 경기마을공동체 국제 컨퍼런스 & 제3회 경기마을공동체 활동가의 날',
    titleEn: '2022 Gyeonggi Community International Conference & 3rd Activists Day',
    description: '5개국 해외 연사 참여, 마을 공동체와 자치 활성화를 위한 학술 토론',
    descriptionEn: 'International academic conference on community governance with speakers from 5 countries',
    images: [],
    year: 2022,
    order: 10,
    date: '2022. 7. 13. - 14.',
    venue: '파주 지지향',
    venueEn: 'Paju Jijihyang',
    organizer: '경기도 / 2022 경기마을주간 추진위원회',
    organizerEn: 'Gyeonggi Province / 2022 Gyeonggi Community Week Committee',
    concept: '5개국 해외 연사들이 참여한 제1회 2022 경기마을공동체 국제 컨퍼런스는 전 사회적으로 요구되는 근본적인 전환의 시대에 마을 공동체와 자치의 활성화를 위한 정책방안을 모색하고 공유하는 학술 토론을 진행하였습니다.',
    planningPoint: '코로나 19 이후 첫 국제 교류 행사로 현장의 한영 동시통역 및 문자통역 작업을 원활히 진행할 수 있는 환경을 만들었고 \'지지향\'이라는 유니크 베뉴와 어울리는 공간을 기획하였습니다.',
  },
  {
    id: 'e11',
    title: '제16회 대한민국청소년박람회',
    titleEn: '16th Korea Youth Fair',
    description: '최초의 온라인 박람회, 누적 시청 28만 회 달성',
    descriptionEn: 'First-ever online fair with 280,000 cumulative views',
    images: [],
    year: 2020,
    order: 11,
    date: '2020. 12. 10. - 12.',
    venue: '부산 벡스코 제1전시장',
    venueEn: 'BEXCO Exhibition Hall 1, Busan',
    organizer: '여성가족부, 부산광역시 / 한국청소년활동진흥원',
    organizerEn: 'Ministry of Gender Equality / Korea Youth Activity Promotion Agency',
    concept: '포스트 코로나 시대 체험과 성장 지속성 확보를 위한 실험적 시도로서 최초의 온라인 박람회 형태로 개최되었으며 사전 녹화 및 생중계를 통해 누적 시청 합계 28만 회를 달성하였습니다.',
    planningPoint: '신규 프로그램 기획으로 풍성한 콘텐츠를 개발하고 친숙한 네이밍을 붙여 행사의 재미 요소를 더하여 다양한 취향을 가진 청소년 참가자들을 만족시키는 박람회가 되었습니다.',
  },
  {
    id: 'e12',
    title: '글로벌 K-스토리 프리 페스티벌',
    titleEn: 'Global K-Story Pre Festival',
    description: '경북을 스토리산업의 메카로 자리매김하기 위한 콘텐츠 행사',
    descriptionEn: 'Content festival positioning Gyeongbuk as the mecca of story industry',
    images: [],
    year: 2022,
    order: 12,
    date: '2022. 10. 20.',
    venue: '전통리조트 구름에 안동',
    venueEn: 'Traditional Resort Gureume, Andong',
    organizer: '경상북도 / 경북콘텐츠진흥원',
    organizerEn: 'Gyeongsangbuk-do / Gyeongbuk Contents Agency',
    concept: '이문열 작가, \'뽀로로\'의 최종일 대표, \'그해 우리는\'의 이나은 작가, \'이상한 변호사 우영우\'의 윤용필 ENA 채널 대표 등 콘텐츠 산업 리더급 연사들이 함께했습니다.',
    planningPoint: '전통적인 콘셉트의 행사장에 어울리는 전시 공간 연출 및 토크쇼, 북콘서트 시나리오 작성을 통해 주최 주관기관의 높은 만족도를 이끌어내었습니다.',
  },
  {
    id: 'e13',
    title: '제19회 대한민국청소년박람회',
    titleEn: '19th Korea Youth Fair',
    description: '3년 만의 오프라인 개최, 연인원 10만 명 이상 참여',
    descriptionEn: 'First offline event in 3 years with over 100,000 attendees',
    images: [],
    year: 2023,
    order: 13,
    featured: true,
    date: '2023. 5. 25. - 5. 27.',
    venue: '인천 송도 컨벤시아',
    venueEn: 'Songdo Convensia, Incheon',
    organizer: '여성가족부, 인천광역시 / 한국청소년활동진흥원',
    organizerEn: 'Ministry of Gender Equality, Incheon / Korea Youth Activity Promotion Agency',
    concept: '3년 만에 오프라인으로 개최된 청소년 최대 축제를 진행하였으며 연인원 10만 명 이상의 청소년 및 학부모가 방문하여 250여 개 부스에서 다양한 청소년 활동을 체험하였습니다.',
    planningPoint: '인공지능 로봇 \'페퍼\'와 VIP들이 대화하는 <페퍼쇼>와 아트봇과 함께하는 <디지털 댄스쇼>, VR 드로잉쇼에 아바타의 움직임을 더한 <메타버스 VR 드로잉쇼>로 풍성한 볼거리를 더하며 개막식의 문을 열었습니다.',
  },
  {
    id: 'e14',
    title: '2025 희망리턴패키지 재기사업화 주관기관 중간보고회',
    titleEn: '2025 Hope Return Package Mid-term Report',
    description: '사업 추진 실적과 예산 집행 현황 점검 보고회',
    descriptionEn: 'Mid-term report reviewing project progress and budget execution',
    images: [],
    year: 2025,
    order: 14,
    date: '2025. 7. 16.',
    venue: '라마다 호텔',
    venueEn: 'Ramada Hotel',
    organizer: '중소벤처기업부, 소상공인시장진흥공단',
    organizerEn: 'Ministry of SMEs and Startups, SEMAS',
    concept: '중소벤처기업부와 소상공인시장진흥공단이 함께한 중간보고회로 사업 추진 실적과 예산 집행 현황을 점검하고 업무 프로세스를 원활히 해줄 전문가의 강의가 진행되었습니다.',
    planningPoint: '참가자 편의를 위한 최적의 등록 프로세스와 동선을 구축하고, 시간대별 다양한 케이터링으로 행사의 만족도를 높였습니다.',
  },
  {
    id: 'e15',
    title: '제18회 대한민국청소년박람회',
    titleEn: '18th Korea Youth Fair',
    description: '메타버스 플랫폼과 오프라인을 결합한 온오프라인 박람회, 110만 명 참여',
    descriptionEn: 'Hybrid fair combining metaverse platforms and offline events with 1.1M participants',
    images: [],
    year: 2022,
    order: 15,
    date: '2022. 5. 26. - 28.',
    venue: '온라인(홈페이지, 유튜브, 오비스, 제페토) / 오프라인(서울 포스트타워, 뷰미디어 드림시어터)',
    venueEn: 'Online (Website, YouTube, oVice, Zepeto) / Offline (Seoul Post Tower)',
    organizer: '여성가족부 / 한국청소년활동진흥원',
    organizerEn: 'Ministry of Gender Equality / Korea Youth Activity Promotion Agency',
    concept: '메타버스 플랫폼(오비스, 제페토, 로블록스)와 홈페이지, 유튜브를 활용한 온라인 진행과 동시에 오프라인 공간을 활용한 인플루언서 강연 등 라이브 행사도 함께 진행하였습니다.',
    planningPoint: '온라인 콘텐츠(영상, 홈페이지, 메타버스) 제작과 함께 오프라인 행사 준비를 비롯한 다각적인 홍보도 진행하여 110만 명 이상의 참여를 이루어내었습니다.',
  },
  {
    id: 'e16',
    title: '제21회 대한민국청소년박람회',
    titleEn: '21st Korea Youth Fair',
    description: '광복 80주년 기념, 안동에서 개최된 청소년 최대 박람회',
    descriptionEn: 'Largest youth fair held in Andong celebrating 80th anniversary of liberation',
    images: [],
    year: 2025,
    order: 16,
    featured: true,
    date: '2025. 5. 23. - 25.',
    venue: '안동국제컨벤션센터',
    venueEn: 'Andong International Convention Center',
    organizer: '여성가족부, 경상북도, 안동시 / 한국청소년활동진흥원',
    organizerEn: 'Ministry of Gender Equality, Gyeongsangbuk-do, Andong / KYAPA',
    concept: '<대한민국 청소년, 역사를 품고 미래를 연다>라는 주제로 광복 80주년을 맞아 개최지인 안동의 역사성과 문화적 특성을 반영한 지역 맞춤형 콘텐츠를 선보이며 큰 호응을 얻었습니다.',
    planningPoint: 'LED 큐브를 이용해 문을 여는 개막 퍼포먼스를 기획하였으며 청소년이 독립 선언문의 양식을 빌려 나라에 대해 직접 생각해보는 이벤트 \'나만의 선언문\'을 기획하여 많은 참가자들의 호응을 얻었습니다.',
  },
  {
    id: 'e17',
    title: '2025 K-디지털 그랜드 챔피언십',
    titleEn: '2025 K-Digital Grand Championship',
    description: 'ICT 유망 스타트업 발굴 및 성장 촉진 피칭 대회',
    descriptionEn: 'Pitching competition for ICT startup discovery and growth',
    images: [],
    year: 2025,
    order: 17,
    date: '2025. 11. 20. / 11. 26. - 27. / 12. 3.',
    venue: '스페이스커넥트, 상암 누리꿈스퀘어, 가빈아트홀',
    venueEn: 'Space Connect, Sangam Nuriggum Square, Gavin Art Hall',
    organizer: '과학기술정보통신부 / 정보통신산업진흥원',
    organizerEn: 'Ministry of Science and ICT / NIPA',
    concept: 'ICT 유망 스타트업의 발굴과 성장을 촉진하기 위해 기획된 행사입니다. 최종 결선 진출팀의 피칭과 기조연설, 시상 및 기업 전시를 통해 혁신 기술 흐름을 공유했습니다.',
    planningPoint: '결선 피칭 중심의 무대를 구성해 스타트업의 시장경쟁력과 성장성을 직관적으로 확인할 수 있도록 운영 전략을 설계했습니다.',
  },
  {
    id: 'e18',
    title: '글로컬 상권 출범식 & 페스타 - 로컬브랜드 플리마켓',
    titleEn: 'Glocal Commercial District Launch & Festa - Local Brand Flea Market',
    description: '전주에서 4일간 진행된 세방화 상권 프로젝트 출범식 및 플리마켓',
    descriptionEn: '4-day glocal commercial project launch and flea market in Jeonju',
    images: [],
    year: 2024,
    order: 18,
    date: '2024. 7. 24. - 27.',
    venue: '전주 문화공판장 작당',
    venueEn: 'Jeonju Cultural Market Jakdang',
    organizer: '중소벤처기업부 / 소상공인시장진흥공단',
    organizerEn: 'Ministry of SMEs and Startups / SEMAS',
    concept: '세방화(글로컬) 상권 프로젝트 출범식 & 페스타가 4일간 진행되었으며 컨퍼런스, 로컬브랜드 토크, 팝업스토어, 문화공연, 플리마켓 등이 개최되었습니다.',
  },
  {
    id: 'e19',
    title: 'K-Culture Innovation 2021, SEOUL 화요장',
    titleEn: 'K-Culture Innovation 2021, SEOUL Hwayojang',
    description: '문화역 서울 284에서 진행된 전통문화 청년 창업 전시 및 데모데이',
    descriptionEn: 'Traditional culture youth startup exhibition and demo day at Culture Station Seoul 284',
    images: [],
    year: 2021,
    order: 19,
    date: '2021. 12. 10. - 12.',
    venue: '문화역 서울 284 RTO',
    venueEn: 'Culture Station Seoul 284 RTO',
    organizer: '문화체육관광부 / 한국공예디자인문화진흥원',
    organizerEn: 'Ministry of Culture / Korea Craft & Design Foundation',
    concept: '스타트업 액셀러레이팅 기업 엔피프틴파트너스의 전통문화 청년 창업 육성 지원사업의 일환으로 진행되는 전시로 기업 제품 전시 및 창업 발표 데모데이 프로그램이 함께 진행되었습니다.',
    planningPoint: '문화역 서울이라는 특수한 공간에서 진행된 전시로 공간과 어울리는 디자인, 연출 작업과 좁은 공간을 활용한 전시월 및 방음 부스 설치를 세심하게 기획하였습니다.',
  },
  {
    id: 'e20',
    title: '2024 경기 사회적경제 박람회',
    titleEn: '2024 Gyeonggi Social Economy Fair',
    description: '제1회 개최, 100개 이상 사회적기업 참여, 3,744명 방문',
    descriptionEn: '1st edition with 100+ social enterprises and 3,744 visitors',
    images: [],
    year: 2024,
    order: 20,
    date: '2024. 8. 23. - 24.',
    venue: '수원컨벤션센터',
    venueEn: 'Suwon Convention Center',
    organizer: '경기도 / 경기도사회적경제원',
    organizerEn: 'Gyeonggi Province / Gyeonggi Social Economy Center',
    concept: '제1회를 맞아 다양한 주제의 콘퍼런스, 세미나, 워크숍, IR 피칭 프로그램, 상담회, 그리고 100개 이상의 사회적기업이 참여하는 전시·체험 프로그램을 기획하고 운영하였습니다.',
    planningPoint: '참가자 모두가 사회적경제의 희망을 적어 날려보는 희망 종이 비행기 퍼포먼스를 통해 \'모두가 함께하는\' 개막식을 연출하였습니다.',
  },
  {
    id: 'e21',
    title: '우리다문화장학재단 장학금 전달식 우리누리 웰컴데이',
    titleEn: 'Woori Multicultural Scholarship Foundation Welcome Day',
    description: '장학금 수여식 및 전문가 특강, 선배 장학생 강연 프로그램',
    descriptionEn: 'Scholarship ceremony with expert lectures and alumni talks',
    images: [],
    year: 2024,
    order: 21,
    date: '2024. 5. 25.',
    venue: '우리은행 본점 비전홀',
    venueEn: 'Woori Bank HQ Vision Hall',
    organizer: '우리다문화장학재단',
    organizerEn: 'Woori Multicultural Scholarship Foundation',
    concept: '<오늘의 우리, 내일의 우리>를 슬로건으로 장학생들의 장학금 수여식, 전문가 특강, 선배 장학생 강연, 축하공연, 도전 우리벨 프로그램을 진행하였습니다.',
  },
  {
    id: 'e22',
    title: '제23차 세계한인비즈니스대회',
    titleEn: '23rd World Korean Business Convention (WKBC 2025)',
    description: '40개국 동포경제인 3,500여명 참여, 약 9,900억원 규모 비즈니스 상담',
    descriptionEn: '3,500+ Korean entrepreneurs from 40 countries, $660M in business deals',
    images: [],
    year: 2025,
    order: 22,
    featured: true,
    date: '2025. 4. 17. - 20.',
    venue: 'GAS South Convention Center, Atlanta',
    venueEn: 'GAS South Convention Center, Atlanta, USA',
    organizer: '재외동포청, 미주한인상공회의소총연합회 / 매일경제, 중소기업중앙회',
    organizerEn: 'Overseas Koreans Agency, KACCF / Maeil Business, KBIZ',
    concept: '전 세계 40개국에서 동포경제인 3,500여명이 참여하여 한상경제권 구축을 논의하였습니다. 총 6억 6000만 달러에 달하는 비즈니스 상담이 이루어졌으며 K-푸드, K-뷰티 상품을 중심으로 4990만 달러의 현장 계약이 체결되었습니다.',
    planningPoint: '기업들의 PR을 위한 \'비즈 세일즈 피칭\', 바이어들의 전시장 투어를 돕는 \'바이어 가이드 투어\' 프로그램을 신설하여 참가자들의 만족도를 높였습니다.',
  },
  {
    id: 'e23',
    title: '제11회 21세기 인문가치포럼',
    titleEn: '11th 21st Century Humanities Value Forum',
    description: '32개국 7,627명 방문, 세계인문도시네트워크 창립총회 개최',
    descriptionEn: '7,627 visitors from 32 countries, World Humanities City Network founding assembly',
    images: [],
    year: 2024,
    order: 23,
    featured: true,
    date: '2024. 10. 31. - 11. 2.',
    venue: '안동국제컨벤션센터',
    venueEn: 'Andong International Convention Center',
    organizer: '문화체육관광부, 경상북도, 안동시 / 한국정신문화재단',
    organizerEn: 'Ministry of Culture, Gyeongsangbuk-do, Andong / Korean Spirit Culture Foundation',
    concept: '"인간다움, 사회적 관계의 회복"을 주제로 32개국 7,627명이 포럼장을 방문했고 온라인으로도 5,796명이 참여했습니다. 3살 어린이부터 105세 철학자에 이르기까지 전 세대의 참여를 끌어냈습니다.',
    planningPoint: '다양한 연령을 고려하여 누구나 참여할 수 있는 대중 세션은 물론 전시, 북큐레이션, 어린이 뮤지컬, 태권도, 대북 퍼포먼스 등 풍성한 부대행사를 준비하였습니다.',
  },
  {
    id: 'e24',
    title: '제1회 대한민국 다문화 페스타',
    titleEn: '1st Korea Multicultural Festa',
    description: '다문화인을 이해하고 함께 성장할 방안을 모색하는 축제',
    descriptionEn: 'Festival for understanding and growing together with multicultural communities',
    images: [],
    year: 2023,
    order: 24,
    date: '2023. 10. 14.',
    venue: '코엑스 그랜드컨퍼런스룸',
    venueEn: 'COEX Grand Conference Room',
    organizer: '연합뉴스, 우리다문화장학재단',
    organizerEn: 'Yonhap News, Woori Multicultural Scholarship Foundation',
    concept: '우리금융그룹 우리다문화장학재단과 연합뉴스가 공동 주최하여 정부 및 유관 기관과 정계·학계 전문가, 다문화 가족 등 300여 명이 참석했습니다.',
    planningPoint: '슬로건 \'우리는 다문화입니다. 다문화는 우리 문화입니다.\'를 제안하여 행사 전반적으로 사용되었으며 참가자들이 친숙하게 느낄 수 있는 네이밍을 활용한 기획을 하였습니다.',
  },
  {
    id: 'e25',
    title: '2025 N STAGE',
    titleEn: '2025 N STAGE',
    description: '스타트업 사업 성장 가능성 검증 및 시장 진입 지원 프로그램',
    descriptionEn: 'Startup growth validation and market entry support program',
    images: [],
    year: 2025,
    order: 25,
    date: '2025. 12. 4.',
    venue: '팀플레이스 홍대',
    venueEn: 'Teamplace Hongdae',
    organizer: '엔피프틴파트너스',
    organizerEn: 'N15 Partners',
    concept: '스타트업의 사업 성장 가능성을 검증하고 시장 진입을 지원하기 위해 개최된 프로그램으로 투자사, 유통사, 마케팅 전문가와의 1:1 멘토링을 중심으로 구성하였습니다.',
    planningPoint: '사전 이해-직접 멘토링-확장 논의의 구조로 프로그램을 설계했습니다. 메인홀과 멘토링 룸을 분리 배치해 동선의 효율성을 높이고 자유 네트워킹 시간을 통해 자연스러운 교류를 유도했습니다.',
  },
  {
    id: 'e26',
    title: '제102회 어린이날 기념행사',
    titleEn: '102nd Children\'s Day Celebration',
    description: '어린이날 기념식 및 청와대 정부 초청 아동행사',
    descriptionEn: 'Children\'s Day ceremony and government-invited children\'s event at Cheongwadae',
    images: [],
    year: 2024,
    order: 26,
    date: '2024. 5. 3.',
    venue: '호텔 나루 엠갤러리 및 용산 어린이정원',
    venueEn: 'Hotel Naru MGallery & Yongsan Children\'s Garden',
    organizer: '보건복지부 / 아동권리보장원',
    organizerEn: 'Ministry of Health and Welfare / National Center for the Rights of the Child',
    concept: '<나는, 내일의 꿈이 될래요!>를 주제로 유공자 포상을 진행하는 기념식과 청와대 연무관에서 진행된 정부 초청 아동행사의 300명 어린이 관리를 플래닝펍이 함께 했습니다.',
    planningPoint: '슬로건과 키 비주얼 기획부터 주제영상, 홍보영상 모션그래픽 제작을 진행하였으며 어린이들의 꿈을 응원하는 \'소망풍선 퍼포먼스\'로 피날레를 진행하였습니다.',
  },
  {
    id: 'e27',
    title: '2025 동국 창업 위크',
    titleEn: '2025 Dongguk Startup Week',
    description: '청년 창업가의 도전정신을 중심으로 한 실전형 창업 페스티벌',
    descriptionEn: 'Hands-on startup festival focused on youth entrepreneurial spirit',
    images: [],
    year: 2025,
    order: 27,
    date: '2025. 11. 5. - 6.',
    venue: '동국대학교 팔정도',
    venueEn: 'Dongguk University Paljungdo',
    organizer: '동국대학교',
    organizerEn: 'Dongguk University',
    concept: '청년 창업가의 도전정신을 중심으로 창업 아이디어의 구체화·실험·공유가 이루어지는 실전형 창업 페스티벌로 기획되었습니다.',
    planningPoint: '캠퍼스 공간을 테마별 존으로 구획해 체험형 동선 중심의 운영 전략을 적용했습니다. 브랜딩 체험형 콘텐츠와 포토/스토리 요소를 결합하여 행사 확산성을 강화했습니다.',
  },
  {
    id: 'e28',
    title: '2024 전통 기록문화 활용 대학생 콘텐츠 공모전',
    titleEn: '2024 Traditional Record Culture University Content Contest',
    description: '10년째 진행된 전통 기록문화 활용 대학생 공모전 피칭 프로모션',
    descriptionEn: '10th year university content contest for traditional record culture',
    images: [],
    year: 2024,
    order: 28,
    date: '2024. 11. 9.',
    venue: '에이치스테이지 소극장',
    venueEn: 'H.Stage Small Theater',
    organizer: '문화체육관광부 / 한국국학진흥원',
    organizerEn: 'Ministry of Culture / Korean Studies Advancement Center',
    concept: '47개 대학, 48개 팀이 지원하여 서류와 면접 심사를 거쳐 8팀의 작품을 최종 심사 후보작으로 선정하였고, 6개월간 1:1 멘토링을 통해 완성된 콘텐츠 기획서를 바탕으로 피칭 프로모션을 선보였습니다.',
    planningPoint: '6개월 간 진행된 공모전 예선-사전 교육-최종 심사를 위한 준비까지 함께하며 전통 기록문화 공모전의 대학생들의 꿈을 플래닝펍이 함께 응원했습니다.',
  },
  {
    id: 'e29',
    title: '2024 대한민국 다문화 페스타',
    titleEn: '2024 Korea Multicultural Festa',
    description: '제2회 다문화 페스타, 오은영 박사 특별강연 등 250명 참여',
    descriptionEn: '2nd Multicultural Festa with Dr. Oh Eun-young lecture, 250 participants',
    images: [],
    year: 2024,
    order: 29,
    date: '2024. 10. 25.',
    venue: '세텍(SETEC) 컨벤션센터',
    venueEn: 'SETEC Convention Center',
    organizer: '연합뉴스, 우리다문화장학재단',
    organizerEn: 'Yonhap News, Woori Multicultural Scholarship Foundation',
    concept: '\'다양성을 잇다, 다문화를 담다\'라는 주제로 개최된 제2회 행사로, 오은영 박사와 일리야 벨랴코프 교수의 특별강연 등 약 250명이 참여했습니다.',
    planningPoint: '다문화 가족센터 종사자들을 타겟으로 고충을 상담하고 보다 나은 지원을 제공할 수 있도록 다양한 정책을 논의하였으며 종사자간 네트워킹 프로그램과 소통형 토크쇼를 기획하였습니다.',
  },
  {
    id: 'e30',
    title: '인구감소지역 관광혁신 아이디어 예선리그',
    titleEn: 'Depopulation Area Tourism Innovation Idea Preliminary League',
    description: '32개 관광 스타트업이 아이디어를 경쟁한 혁신 프로젝트',
    descriptionEn: 'Innovation project with 32 tourism startups competing with ideas',
    images: [],
    year: 2022,
    order: 30,
    date: '2022. 8. 30.',
    venue: '강남 슈피겐홀',
    venueEn: 'Gangnam Spigen Hall',
    organizer: '문화체육관광부 / 한국관광공사',
    organizerEn: 'Ministry of Culture / Korea Tourism Organization',
    concept: '코로나19로 침체된 지역 관광을 활성화 하기 위한 혁신적인 아이디어를 교류하기 위해 개최되었으며 총 32개 스타트업이 아이디어를 경쟁했습니다.',
    planningPoint: '인구감소지역 관광혁신 아이디어 예선리그에 맞는 네이밍 \'BETTER : 里\'를 제안하여 채택되었습니다.',
  },
  {
    id: 'e31',
    title: 'P4G 서울 녹색미래 정상회의 물 기본세션',
    titleEn: 'P4G Seoul Green Future Summit Water Session',
    description: '12개국 참여 녹색미래 정상회의 물 분야 기본세션',
    descriptionEn: 'Water session at the Green Future Summit with 12 countries',
    images: [],
    year: 2021,
    order: 31,
    date: '2021. 5. 30. - 31.',
    venue: 'DDP(동대문디자인플라자)',
    venueEn: 'DDP (Dongdaemun Design Plaza)',
    organizer: '환경부 / 한국물포럼',
    organizerEn: 'Ministry of Environment / Korea Water Forum',
    concept: '12개국이 참여한 P4G 서울 녹색미래 정상회의의 첫 번째 기본 세션으로 물 분야의 각국 장관급 연사들과 글로벌 청년 대표단이 온라인 화상회의 방식으로 토론을 진행하였습니다.',
    planningPoint: '현장의 좌장과 기조연사 사이로 LED 세로 패널을 배치함으로써 현장감을 강화하여 타 세션들과의 차별화된 영상을 연출하였습니다.',
  },
  {
    id: 'e32',
    title: '찾아가는 다문화 직업인 진로콘서트(수도권편)',
    titleEn: 'Mobile Multicultural Career Concert (Seoul Metropolitan Area)',
    description: '다문화 직업인과 함께하는 청소년 진로탐색 콘서트',
    descriptionEn: 'Youth career exploration concert with multicultural professionals',
    images: [],
    year: 2024,
    order: 32,
    date: '',
    venue: '',
    venueEn: '',
    organizer: '',
    organizerEn: '',
    concept: '학생들이 미래 유망 직업 분야를 스스로 탐색하고 진로를 준비할 수 있는 기회의 장으로, 신산업 분야 전문가 강연, 다문화직업인과 함께하는 이야기콘서트, 직업체험존, 학과체험존, 진로상담존 등이 운영되었습니다.',
    planningPoint: '다양한 직업과 성격을 가진 직업인 패널(파트리샤, 한현민, 이미쉘, 레오란타 등)들을 섭외하여 참가자가 즐길 수 있는 토크콘서트를 기획하였습니다.',
  },
  {
    id: 'e33',
    title: '제7회 21세기인문가치포럼',
    titleEn: '7th 21st Century Humanities Value Forum',
    description: '동아시아 유교권 국가 및 글로벌 연사들이 참여한 인문가치 포럼',
    descriptionEn: 'Humanities forum with speakers from East Asian Confucian nations and globally',
    images: [],
    year: 2020,
    order: 33,
    date: '2020. 10. 30. - 11. 1.',
    venue: '안동 전통리조트 구름에',
    venueEn: 'Andong Traditional Resort Gureume',
    organizer: '문화체육관광부, 경상북도, 안동시 / 한국정신문화재단',
    organizerEn: 'Ministry of Culture, Gyeongsangbuk-do, Andong / Korean Spirit Culture Foundation',
    concept: '동아시아 유교권 국가 및 글로벌 연사들을 초청하여 현대 사회의 다양한 인문가치에 대하여 논의하는 포럼으로 누구나 참여할 수 있는 지역 축제로 운영되었습니다.',
    planningPoint: '포럼의 주제인 \'문화 다양성 시대의 사회적 가치\'에 맞게 다양한 성별, 나이, 종교, 인종의 인물을 섭외하여 주제 영상을 제작하고 현장 VIP들과 영상 속 인물이 함께 개막을 알리는 퍼포먼스를 연출했습니다.',
  },
  {
    id: 'e34',
    title: '2022 한국문화축제 더케이 팬 페어 & 스테이지 in 잠실',
    titleEn: '2022 Korean Culture Festival The K Fan Fair & Stage in Jamsil',
    description: '한류 팬과 아티스트가 만드는 일주일간의 문화축제',
    descriptionEn: 'Week-long cultural festival created by Hallyu fans and artists',
    images: [],
    year: 2022,
    order: 34,
    date: '2022. 10. 2. - 8.',
    venue: '잠실종합운동장 보조경기장',
    venueEn: 'Jamsil Sports Complex Auxiliary Stadium',
    organizer: '문화체육관광부 / 한국국제문화교류진흥원',
    organizerEn: 'Ministry of Culture / Korean Foundation for International Cultural Exchange',
    concept: '인디, K-POP, 힙합, DJ, 인플루언서 등 다양한 라인업이 참여하여 일주일 간 진행되었고 뷰티, 패션 분야의 공모전과 한류연관산업존도 함께 운영되었습니다.',
    planningPoint: '우천으로 인한 기상악화에도 일주일 간 다양한 라인업으로 운영하였으며 \'팬덤메이킹스페이스\'와 \'더케이 플로깅\'을 기획, 운영하여 참가자 만족도를 높였습니다.',
  },
  {
    id: 'e35',
    title: '2022 소상공인 창업성장주간',
    titleEn: '2022 Small Business Startup Growth Week',
    description: '소상공인 지원사업 성과 공유 및 네트워킹, SoTY 선정',
    descriptionEn: 'Small business support achievements sharing and SoTY awards',
    images: [],
    year: 2022,
    order: 35,
    date: '2022. 12. 7. - 9.',
    venue: '카페 FYI',
    venueEn: 'Cafe FYI',
    organizer: '중소벤처기업부 / 소상공인시장진흥공단',
    organizerEn: 'Ministry of SMEs and Startups / SEMAS',
    concept: '소상공인 창업 및 성장 지원사업의 주요 성과를 공유하고 네트워킹을 통해 새로운 성장 전략을 모색하고자 개최되었으며 최고의 소상공인을 뽑는 SoTY를 진행하였습니다.',
    planningPoint: '오디션 형태의 프로그램들은 발표 직후 심사위원 점수를 실시간으로 취합해 공개하는 쇼 형식으로 진행하였으며 모의투자 프로그램을 활용한 이벤트를 진행했습니다.',
  },
  {
    id: 'e36',
    title: '글로벌 AI 컨퍼런스 AICON 광주 2023',
    titleEn: 'Global AI Conference AICON Gwangju 2023',
    description: 'IBM, 구글 등 글로벌 연사와 함께한 3일간의 AI 컨퍼런스',
    descriptionEn: '3-day AI conference with global speakers from IBM, Google, and more',
    images: [],
    year: 2023,
    order: 36,
    date: '2023. 11. 1. - 3.',
    venue: '광주과학기술원 오룡관',
    venueEn: 'GIST Oryonggwan, Gwangju',
    organizer: '과학기술정보통신부, 광주광역시, 정보통신산업진흥원 / 인공지능산업융합사업단',
    organizerEn: 'Ministry of Science and ICT, Gwangju Metropolitan City, NIPA',
    concept: 'AI 중심도시 광주에서 개최되어 IBM, 구글, 자이스, 재규어랜드로버 등 국외 유명 연사들과 국내 인공지능 오피니언 리더들의 강연과 AI 스타트업들의 전시가 3일간 진행되었습니다.',
    planningPoint: '행사의 모객을 위해 저명한 기조연사들을 섭외하였으며 3일간 한국어, 영어 채널 온라인 송출을 병행하여 온오프라인 참가자의 만족도를 높였습니다. 홀로그램과 미디어를 활용한 오프닝 퍼포먼스를 진행하였습니다.',
  },
  {
    id: 'e37',
    title: '2022 강한소상공인 성장지원 1차 오디션',
    titleEn: '2022 Strong Small Business Growth Support 1st Audition',
    description: '1,324명 지원, 13.2:1 경쟁률의 소상공인 오디션 쇼',
    descriptionEn: 'Small business audition show with 1,324 applicants and 13.2:1 competition ratio',
    images: [],
    year: 2022,
    order: 37,
    date: '2022. 6. 28. - 29.',
    venue: '노들섬 라이브하우스',
    venueEn: 'Nodeul Island Live House',
    organizer: '중소벤처기업부 / 소상공인시장진흥공단',
    organizerEn: 'Ministry of SMEs and Startups / SEMAS',
    concept: '1,324명의 소상공인이 지원해 13.2:1의 높은 경쟁률을 기록했고, 100팀이 선정되어 라이브 오디션 쇼 형식으로 진행되었습니다.',
    planningPoint: '7분 발표, 5분 질의응답으로 빠르게 진행되는 만큼 발표자 관리와 운영이 중요한 포인트였으며 플래닝펍은 이를 매뉴얼화하여 완벽하게 운영하였습니다.',
  },
  {
    id: 'e38',
    title: '창업진흥원 사내벤처 육성 프로그램 네트워킹데이',
    titleEn: 'KISED Internal Venture Program Networking Day',
    description: '창업진흥원 사내벤처 육성 프로그램 참여 기업 네트워킹',
    descriptionEn: 'Networking event for KISED internal venture program participants',
    images: [],
    year: 2025,
    order: 38,
    date: '',
    venue: '',
    venueEn: '',
    organizer: '창업진흥원',
    organizerEn: 'Korea Institute of Startup & Entrepreneurship Development',
  },
];
